let nom = "   Fatima   ";
let age = "23";
let email = "fatima@example";
let scoreJeu = "150pts";
let estAdmin = "false";
let derniereConnexion = null;
let nombreConnexions = "0";

let nomCorrige = nom.trim();
if (nomCorrige === "") nomCorrige = "Inconnu";
let ageCorrige = parseInt(age);
let ageStatus = (Number.isNaN(ageCorrige) || ageCorrige <= 0) ? "invalide" : "valide";
let indexAt = email.indexOf("@");
let emailValide = indexAt !== -1 && email.indexOf(".", indexAt) !== -1;
let scoreCorrige = parseInt(scoreJeu);
if (Number.isNaN(scoreCorrige)) scoreCorrige = 0;
let estAdminBool = (estAdmin === "true");
let connexionStatus = derniereConnexion ?? "Jamais connecté";
let nbConnexionsNum = Number(nombreConnexions);
let nbConnexionsAffiche = (nbConnexionsNum === 0) ? "Aucune connexion" : nbConnexionsNum;

console.log("===== RAPPORT UTILISATEUR =====");
console.log(`nom              : "${nomCorrige}" (corrigé : espaces supprimés)`);
console.log(`age              : ${ageCorrige} (${ageStatus})`);
console.log(`email            : "${email}" (${emailValide ? "valide" : "invalide : pas de point après @"})`);
console.log(`scoreJeu         : ${scoreCorrige} (extrait depuis "${scoreJeu}")`);
console.log(`estAdmin         : ${estAdminBool} (attention : Boolean("false") = true, conversion manuelle requise)`);
console.log(`derniereConnexion: "${connexionStatus}" (valeur par défaut via ??)`);
console.log(`nombreConnexions : "${nbConnexionsAffiche}" (${nbConnexionsNum} après conversion)`);
console.log("================================");